/*
 * This source file was generated by the Gradle 'init' task
 */
package kiosk;

import java.util.InputMismatchException;
import java.util.List;
import java.util.Scanner;

import kiosk.models.MenuItem;

public class App {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        
        List<MenuItem> menuItems = List.of(
                new MenuItem("ShackBurger", 6.9, "토마토, 양상추, 쉑소스가 토핑된 치즈버거"),
                new MenuItem("SmokeShack", 8.9, "베이컨, 체리 페퍼에 쉑소스가 토핑된 치즈버거"),
                new MenuItem("Cheeseburger", 6.9, "포테이토 번과 비프패티, 치즈가 토핑된 치즈버거"),
                new MenuItem("Hamburger", 5.4, "비프패티를 기반으로 야채가 들어간 기본버거")
        );

        while (true) {
            System.out.println("[ SHAKESHACK MENU ]");

            for (int i = 0; i < menuItems.size(); i++) {
                System.out.println(i + 1 + ". " + menuItems.get(i));
            }

            System.out.println("0. 종료 | 종료");

            int choice;

            try {
                choice = sc.nextInt();
            } catch (InputMismatchException e) {
                System.out.println("잘못된 입력입니다. 숫자를 입력해주세요.");
                // 잘못 입력된 버퍼를 청소
                sc.next();
                continue;
            }

            if(choice == 0) {
                System.out.println("프로그램을 종료합니다.");
                break;
            }

            if(choice < 1 || choice > menuItems.size()) {
                System.out.println("잘못된 선택입니다.");
                continue;
            }
            
            MenuItem selectedItem = menuItems.get(choice - 1);
            System.out.println(selectedItem.name() + "를 선택하셨습니다.");
        }
    }
}
